# Spelling Creator, as a single self-hosted image.
#
# Builds the SPA and the docs site, then runs the Node API (apps/api/src/node/
# server.js), which serves both from disk alongside the API itself. See
# /docs/monorepo/self-hosting for what this host does and does not provide, and
# docker-compose.yml for a worked example with Postgres, PostgREST, GoTrue and
# MinIO around it.
#
#   docker build -t spelling-creator \
#     --build-arg VITE_API_URL=https://spelling.example.com \
#     --build-arg VITE_SUPABASE_URL=https://spelling.example.com \
#     --build-arg VITE_SUPABASE_ANON_KEY=... .
#
# The VITE_* values are BUILD arguments, not runtime environment: Vite
# substitutes them into the bundle at build time, so they are baked into the
# image and an instance pointed at different URLs needs its own build. That is a
# property of building a static SPA, not a choice made here.

# syntax=docker/dockerfile:1

# ---------------------------------------------------------------------------
# Build: install the workspace, build the SPA and the docs into apps/web/dist.
# ---------------------------------------------------------------------------
FROM node:24-alpine AS builder

ENV PNPM_HOME=/pnpm
ENV PATH=$PNPM_HOME:$PATH
RUN corepack enable

WORKDIR /app

# Manifests first, so the install layer is cached independently of the source and
# a code-only change doesn't reinstall the world. The patches directory is copied
# with them because pnpm applies patchedDependencies during install.
COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./
COPY patches ./patches
COPY apps/api/package.json ./apps/api/
COPY apps/web/package.json ./apps/web/
COPY apps/mcp/package.json ./apps/mcp/
COPY apps/docs/package.json ./apps/docs/
COPY packages/core/package.json ./packages/core/

RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install --frozen-lockfile

COPY . .

# Read by Vite at build time and substituted into the bundle. Vite exposes any
# environment variable with the VITE_ prefix, so these need no .env file.
ARG VITE_API_URL=""
ARG VITE_SUPABASE_URL=""
ARG VITE_SUPABASE_ANON_KEY=""
ARG VITE_TURNSTILE_SITE_KEY=""
ARG VITE_GOOGLE_CLIENT_ID=""
ENV VITE_API_URL=$VITE_API_URL \
    VITE_SUPABASE_URL=$VITE_SUPABASE_URL \
    VITE_SUPABASE_ANON_KEY=$VITE_SUPABASE_ANON_KEY \
    VITE_TURNSTILE_SITE_KEY=$VITE_TURNSTILE_SITE_KEY \
    VITE_GOOGLE_CLIENT_ID=$VITE_GOOGLE_CLIENT_ID

# The web build emits both halves: dist (the SPA) and dist-ssr (the server bundle
# routes/ssr.js imports). Docs must come second — the SPA build empties dist, so
# building docs first would delete them again.
RUN pnpm --filter @spelling-creator/web build \
 && pnpm --filter @spelling-creator/docs build

# Drop the build-only dependencies now that the bundles exist. Doing it here
# rather than reinstalling in the runtime stage keeps the pnpm store mount — and
# the workspace's symlink layout — intact.
RUN pnpm install --frozen-lockfile --prod --ignore-scripts

# ---------------------------------------------------------------------------
# Run.
# ---------------------------------------------------------------------------
FROM node:24-alpine AS runtime

ENV NODE_ENV=production \
    PORT=8787 \
    HOST=0.0.0.0 \
    WEB_DIST=/app/apps/web/dist

WORKDIR /app

# `node` is a non-root user the base image already provides. Nothing here is
# written to at runtime — the process is stateless — so it needs no ownership
# beyond read access.
COPY --from=builder --chown=node:node /app /app

USER node
EXPOSE 8787

# /robots.txt is generated by the API but needs neither the database nor object
# storage, so it answers 200 exactly when the process is up and routing — which
# is what a liveness check should mean, rather than also failing when Postgres
# is briefly unreachable.
HEALTHCHECK --interval=30s --timeout=5s --start-period=10s --retries=3 \
  CMD node -e "fetch('http://127.0.0.1:'+(process.env.PORT||8787)+'/robots.txt').then(r=>process.exit(r.ok?0:1)).catch(()=>process.exit(1))"

CMD ["node", "apps/api/src/node/server.js"]
