// Whether the viewport is phone-width, which is what decides between the
// sidebar-as-sheet and the sidebar-beside-the-page (see ui/sidebar.jsx).
//
// Generated by the shadcn CLI, with one change: the CLI's version sets up a
// media query and then answers with `window.innerWidth`, so the listener and
// the value it produces are two different measurements of the same threshold.
// They disagree wherever a classic scrollbar is counted — innerWidth includes
// it, the media query does not — which is a state that flickers exactly at the
// breakpoint. `mql.matches` is the same source that fired the event.
//
// It starts `undefined` and resolves in an effect on purpose: /hub, /hub/:id
// and /users/:id are server-rendered (apps/api/src/routes/ssr.js), so the
// Worker and the browser's first render have to agree, and neither has a
// viewport to consult. Both begin at "not mobile".

import * as React from "react";

const MOBILE_BREAKPOINT = 768;

export function useIsMobile() {
  const [isMobile, setIsMobile] = React.useState(undefined);

  React.useEffect(() => {
    const mql = window.matchMedia(`(max-width: ${MOBILE_BREAKPOINT - 1}px)`);
    const onChange = (event) => setIsMobile(event.matches);
    mql.addEventListener("change", onChange);
    setIsMobile(mql.matches);
    return () => mql.removeEventListener("change", onChange);
  }, []);

  return !!isMobile;
}
