// Service-worker registration and the UI around it.
//
// The worker itself is generated by vite-plugin-pwa (see the VitePWA block in
// vite.config.js) and only exists in a production build; `virtual:pwa-register`
// is a no-op stub in dev, so this module is safe to mount unconditionally.
//
// Registration is `registerType: "prompt"`, which means a newly deployed build
// waits rather than taking over. That is deliberate: this app is an editor, and
// activating a new worker reloads the page. So we surface it as a toast the
// person can dismiss and come back to when they aren't mid-lesson.

import { useEffect, useRef } from "react";
import { useTranslation } from "react-i18next";
import { toast } from "sonner";
import { useRegisterSW } from "virtual:pwa-register/react";

// How often to ask the browser whether a new build has been deployed. Without
// this, a tab left open for days only notices on a manual reload — and an
// installed PWA is exactly the case where a "tab" can stay open indefinitely.
const UPDATE_CHECK_INTERVAL = 60 * 60 * 1000; // 1 hour

export default function ServiceWorkerPrompt() {
  const { t } = useTranslation("common");
  const {
    needRefresh: [needRefresh, setNeedRefresh],
    updateServiceWorker,
  } = useRegisterSW({
    onRegisteredSW(_url, registration) {
      if (!registration) return;
      setInterval(() => {
        // Only poll when we're actually online; an offline update() just
        // rejects, and there is nothing useful to do about it.
        if (navigator.onLine) registration.update();
      }, UPDATE_CHECK_INTERVAL);
    },
  });

  // Toast IDs are stable so a re-render can't stack duplicates, and so the
  // effect's cleanup can dismiss the exact toast it created.
  const shown = useRef(false);

  useEffect(() => {
    if (!needRefresh || shown.current) return;
    shown.current = true;
    toast(t("pwa.updateTitle"), {
      id: "sw-update",
      description: t("pwa.updateDescription"),
      duration: Infinity,
      action: {
        label: t("pwa.updateAction"),
        // Reloads the page once the waiting worker has taken control.
        onClick: () => updateServiceWorker(true),
      },
      onDismiss: () => {
        // Let it be offered again on the next update check rather than never
        // again for the life of the tab.
        shown.current = false;
        setNeedRefresh(false);
      },
    });
  }, [needRefresh, setNeedRefresh, updateServiceWorker, t]);

  return null;
}
